import React from 'react';
import {
    Users,
    Bed,
    Stethoscope,
    DollarSign,
    Activity,
    TrendingUp,
    CalendarCheck,
    Clock
} from 'lucide-react';

export default function DashboardOverview({ setActiveTab }) {
    // Top summary counters
    const stats = [
        { label: "Today's Total Patients", value: '42', change: '+12% vs yesterday', icon: Users, color: 'blue' },
        { label: 'Available Beds', value: '18 / 30', change: '60% occupancy', icon: Bed, color: 'emerald' },
        { label: 'Doctors On Duty', value: '8 Active', change: 'All departments', icon: Stethoscope, color: 'indigo' },
        { label: "Today's Revenue", value: '$12,450', change: 'AUD billing today', icon: DollarSign, color: 'amber' },
    ];

    // Recent emergency and clinical activity log
    const recentEvents = [
        { patient: 'David Warner', action: 'Admitted to ICU Room 102', time: '10 mins ago', status: 'In Progress', statusColor: 'amber' },
        { patient: 'Sarah Jenkins', action: 'Prescription generated by Dr. Steve', time: '25 mins ago', status: 'Completed', statusColor: 'emerald' },
        { patient: 'Michael Clarke', action: 'Blood Pathology Test Ordered', time: '40 mins ago', status: 'Lab Queue', statusColor: 'blue' },
        { patient: 'Emma Watson', action: 'Discharge Summary & Invoice Paid', time: '1 hour ago', status: 'Settled', statusColor: 'emerald' }
    ];

    return (
        <div className="space-y-6">
            {/* Header banner */}
            <div className="flex flex-col sm:flex-row sm:items-center justify-between pb-2 border-b border-slate-200/80 gap-4">
                <div>
                    <h2 className="text-xl font-bold text-slate-900">Hospital Executive Dashboard</h2>
                    <p className="text-xs text-slate-500">Real-time facility snapshot, occupancy rates, and daily revenue metrics.</p>
                </div>
                <div className="flex items-center gap-2">
                    <span className="flex items-center gap-1.5 px-3 py-1 bg-emerald-50 text-emerald-700 text-xs font-semibold rounded-full border border-emerald-200">
                        <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></span>
                        Live Metrics
                    </span>
                </div>
            </div>

            {/* 4 Primary KPI metric cards */}
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
                {stats.map((s, idx) => {
                    const IconComponent = s.icon;
                    return (
                        <div key={idx} className="bg-white border border-slate-200/80 rounded-2xl p-5 shadow-xs hover:shadow-md transition">
                            <div className="flex items-center justify-between">
                                <span className="text-xs font-bold text-slate-400 uppercase tracking-wider">{s.label}</span>
                                <div className="p-2.5 rounded-xl bg-slate-50 text-blue-600 border border-slate-100">
                                    <IconComponent className="w-4 h-4" />
                                </div>
                            </div>
                            <h3 className="text-2xl font-black text-slate-900 mt-2">{s.value}</h3>
                            <p className="text-xs text-slate-400 font-medium mt-1 flex items-center gap-1">
                                <TrendingUp className="w-3 h-3 text-emerald-500" /> {s.change}
                            </p>
                        </div>
                    );
                })}
            </div>

            {/* Two column layout: Department Occupancy & Live Activity Feed */}
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                {/* Department Bed Occupancy Progress Bars */}
                <div className="bg-white border border-slate-200/80 rounded-2xl p-6 shadow-xs space-y-4">
                    <h3 className="text-base font-bold text-slate-900 flex items-center gap-2">
                        <Activity className="w-4 h-4 text-blue-600" /> Bed Occupancy by Unit
                    </h3>
                    <p className="text-xs text-slate-400">Current bed usage across all departments.</p>

                    <div className="space-y-4 pt-2">
                        <div>
                            <div className="flex justify-between text-xs font-semibold text-slate-700 mb-1">
                                <span>Cardiology ICU</span>
                                <span>80% Occupied</span>
                            </div>
                            <div className="w-full bg-slate-100 h-2.5 rounded-full overflow-hidden">
                                <div className="bg-rose-500 h-2.5 rounded-full" style={{ width: '80%' }}></div>
                            </div>
                        </div>

                        <div>
                            <div className="flex justify-between text-xs font-semibold text-slate-700 mb-1">
                                <span>General Ward</span>
                                <span>45% Occupied</span>
                            </div>
                            <div className="w-full bg-slate-100 h-2.5 rounded-full overflow-hidden">
                                <div className="bg-blue-600 h-2.5 rounded-full" style={{ width: '45%' }}></div>
                            </div>
                        </div>

                        <div>
                            <div className="flex justify-between text-xs font-semibold text-slate-700 mb-1">
                                <span>Emergency Triage</span>
                                <span>90% Critical</span>
                            </div>
                            <div className="w-full bg-slate-100 h-2.5 rounded-full overflow-hidden">
                                <div className="bg-amber-500 h-2.5 rounded-full" style={{ width: '90%' }}></div>
                            </div>
                        </div>
                    </div>

                    <button
                        onClick={() => setActiveTab('rooms')}
                        className="w-full mt-4 py-2 border border-slate-200 rounded-xl text-xs font-bold text-slate-700 hover:bg-slate-50 transition"
                    >
                        Manage Rooms & Beds &rarr;
                    </button>
                </div>

                {/* Real-time Hospital Timeline Activity */}
                <div className="lg:col-span-2 bg-white border border-slate-200/80 rounded-2xl p-6 shadow-xs space-y-4">
                    <div className="flex items-center justify-between">
                        <h3 className="text-base font-bold text-slate-900 flex items-center gap-2">
                            <Clock className="w-4 h-4 text-blue-600" /> Live Patient Event Stream
                        </h3>
                        <span className="text-xs text-slate-400 font-medium">Automatic updates</span>
                    </div>

                    <div className="divide-y divide-slate-100">
                        {recentEvents.map((event, idx) => (
                            <div key={idx} className="py-3 flex items-center justify-between">
                                <div>
                                    <p className="text-sm font-bold text-slate-800">{event.patient}</p>
                                    <p className="text-xs text-slate-500">{event.action}</p>
                                </div>
                                <div className="text-right">
                                    <span className={`inline-block text-[10px] font-bold px-2 py-0.5 rounded-full border ${
                                        event.statusColor === 'emerald' ? 'bg-emerald-50 text-emerald-700 border-emerald-200' :
                                            event.statusColor === 'amber' ? 'bg-amber-50 text-amber-700 border-amber-200' :
                                                'bg-blue-50 text-blue-700 border-blue-200'
                                    }`}>
                                        {event.status}
                                    </span>
                                    <p className="text-[10px] text-slate-400 font-mono mt-0.5">{event.time}</p>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            </div>
        </div>
    );
}